/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package os_group_3;

import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static os_group_3.db_connect.frame;

/**
 *
 * @author johnl
 */
public class AddVisitor extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public AddVisitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        relationship = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        pdllastname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        pdlfirstname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OS_Group3");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 53, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 250, 202));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 90, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 250, 202));
        jLabel4.setText("Middle Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 250, 202));
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 90, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 250, 202));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 250, 202));
        jLabel7.setText("Contact No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 250, 202));
        jLabel8.setText("Inmate First Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 130, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 250, 202));
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 60, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 250, 202));
        jLabel10.setText("Relationship");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 130, -1));

        relationship.setBackground(new java.awt.Color(255, 250, 202));
        relationship.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        relationship.setForeground(new java.awt.Color(0, 0, 0));
        relationship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Family", "Acquaintance", "Friend", "Relative" }));
        relationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationshipActionPerformed(evt);
            }
        });
        jPanel1.add(relationship, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 180, 40));

        jLabel11.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 250, 202));
        jLabel11.setText("Age");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 40, -1));

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 250, 202));
        jLabel12.setText("Inmate Last Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 130, -1));

        gender.setBackground(new java.awt.Color(255, 250, 202));
        gender.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.setSelectedIndex(-1);
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        jButton1.setBackground(new java.awt.Color(103, 146, 137));
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 90, 40));

        jButton2.setBackground(new java.awt.Color(103, 146, 137));
        jButton2.setText("see list");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 90, 40));

        jButton3.setBackground(new java.awt.Color(103, 146, 137));
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 90, 40));

        age.setBackground(new java.awt.Color(255, 250, 202));
        age.setForeground(new java.awt.Color(0, 0, 0));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 60, 40));

        pdllastname.setBackground(new java.awt.Color(255, 250, 202));
        pdllastname.setForeground(new java.awt.Color(0, 0, 0));
        pdllastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdllastnameActionPerformed(evt);
            }
        });
        jPanel1.add(pdllastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 240, 50));

        middlename.setBackground(new java.awt.Color(255, 250, 202));
        middlename.setForeground(new java.awt.Color(0, 0, 0));
        middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameActionPerformed(evt);
            }
        });
        jPanel1.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 240, 50));

        lastname.setBackground(new java.awt.Color(255, 250, 202));
        lastname.setForeground(new java.awt.Color(0, 0, 0));
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 240, 50));

        address.setBackground(new java.awt.Color(255, 250, 202));
        address.setForeground(new java.awt.Color(0, 0, 0));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 240, 50));

        firstname.setBackground(new java.awt.Color(255, 250, 202));
        firstname.setForeground(new java.awt.Color(0, 0, 0));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 240, 50));

        contactno.setBackground(new java.awt.Color(255, 250, 202));
        contactno.setForeground(new java.awt.Color(0, 0, 0));
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 240, 50));

        pdlfirstname.setBackground(new java.awt.Color(255, 250, 202));
        pdlfirstname.setForeground(new java.awt.Color(0, 0, 0));
        pdlfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdlfirstnameActionPerformed(evt);
            }
        });
        jPanel1.add(pdlfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 240, 50));

        jPanel2.setBackground(new java.awt.Color(255, 250, 202));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Visitor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 70));

        imageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("Click here to upload an image..");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        imageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, 330));

        logo.setBackground(new java.awt.Color(255, 250, 202));
        logo.setIcon((new javax.swing.ImageIcon("images\\bjmpLogo.png")));
jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 430, 400));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        firstname.setText(variables.first_name);
        middlename.setText(variables.middle_name);
        lastname.setText(variables.last_name);
        address.setText(variables.address);
        age.setText(variables.age);
        contactno.setText(variables.contact_number);
        gender.setSelectedItem(variables.gender);
        
         // Decode Base64 string to bytes
        byte[] imageBytes = Base64.getDecoder().decode(variables.image);
        
        ImageIcon originalImageIcon = new ImageIcon(imageBytes);
        Image originalImage = originalImageIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        imageLabel.setIcon(scaledImageIcon);
        imageLabel.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void relationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationshipActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocalDate currentdate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = currentdate.format(formatter);

        LocalTime currentTime = LocalTime.now();
        DateTimeFormatter timeformatter = DateTimeFormatter.ofPattern("hh:mm a");
        String formattedTime = currentTime.format(timeformatter);

        LocalTime newTime = currentTime.plusMinutes(15);
        String timeOut = newTime.format(timeformatter);

        try {
                    // Continue with the rest of the data upload
                    String documentName = firstname.getText() + " " + middlename.getText() + " " + lastname.getText();
                    Map<String, Object> data = new HashMap<>();
                    data.put("first_name", firstname.getText());
                    data.put("middle_name", middlename.getText());
                    data.put("last_name", lastname.getText());
                    data.put("address", address.getText());
                    data.put("age", age.getText());
                    data.put("gender", gender.getSelectedItem());
                    data.put("contact_no", contactno.getText());
                    data.put("is_valid", true);
                    data.put("pdl_firstname", pdlfirstname.getText());
                    data.put("pdl_lastname", pdllastname.getText());
                    data.put("relationship", relationship.getSelectedItem());
                    data.put("date_of_visit", formattedDate);
                    data.put("time_of_visit", formattedTime);
                    data.put("time_out", timeOut);
                    data.put("image", variables.image);
                 

                    DocumentReference docRef = db_connect.db.collection("visitor").document(documentName);
                    docRef.set(data);

                    firstname.setText("");
                    middlename.setText("");
                    address.setText("");
                    lastname.setText("");
                    age.setText("");
                    gender.setSelectedIndex(0);
                    contactno.setText("");
                    pdlfirstname.setText("");
                    pdllastname.setText("");
                    relationship.setSelectedIndex(0);
                    imageLabel.setIcon(null);
                    imageLabel.setText("Click here to upload an image..");

                    JOptionPane.showMessageDialog(frame, "Information added successfully!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame, "Error occurred when adding information",
                    "Error",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        }//GEN-LAST:event_jButton1ActionPerformed
    private String convertImageToBase64(File imageFile) throws IOException {
        byte[] fileBytes = new byte[(int) imageFile.length()];
        FileInputStream fileInputStream = new FileInputStream(imageFile);
        fileInputStream.read(fileBytes);
        fileInputStream.close();
        return Base64.getEncoder().encodeToString(fileBytes);
    }    
    
    private boolean isValidImageFile(File file) {
                String[] allowedExtensions = {"jpg", "jpeg", "png", "gif"};
                String fileName = file.getName().toLowerCase();

                for (String extension : allowedExtensions) {
                    if (fileName.endsWith("." + extension)) {
                        return true;
                    }
                }

                return false;
            }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         show(false);
        VisitorList form = new VisitorList();
        form.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
show(false);
       VisitingSchedule form = new VisitingSchedule();
       form.show();    }//GEN-LAST:event_jButton3ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void pdllastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdllastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdllastnameActionPerformed

    private void middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void pdlfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdlfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdlfirstnameActionPerformed

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        // Create a file chooser dialog
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Image");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif"));

        // Show the file chooser dialog
        int returnValue = fileChooser.showOpenDialog(null);

        // If the user chooses a file, display it in the JLabel
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // Read the selected image file as bytes
                byte[] imageBytes = Files.readAllBytes(selectedFile.toPath());

                // Convert the image bytes to a Base64 encoded string
                variables.image = Base64.getEncoder().encodeToString(imageBytes);
                
                // Decode the Base64 string and set the image in the JLabel
                ImageIcon originalImageIcon = new ImageIcon(imageBytes);
                Image originalImage = originalImageIcon.getImage();
                Image scaledImage = originalImage.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                imageLabel.setIcon(scaledImageIcon);
                imageLabel.setText("");
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error reading image file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_imageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVisitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField middlename;
    private javax.swing.JTextField pdlfirstname;
    private javax.swing.JTextField pdllastname;
    private javax.swing.JComboBox<String> relationship;
    // End of variables declaration//GEN-END:variables
}
