/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package os_group_3;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.Query;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import java.awt.List;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johnl
 */
public class VisitorList extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public VisitorList() {
        initComponents();
    }

    
    LocalDate currentDate = LocalDate.now();
    DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    String formattedDate = currentDate.format(formatter2);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new CustomComponents.button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        showDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel1 = new CustomComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        addVisitor = new CustomComponents.button.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OS_Group3");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 53, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(103, 146, 137));
        backButton.setForeground(new java.awt.Color(255, 250, 202));
        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        backButton.setRound(20);
        backButton.setShadowColor(new java.awt.Color(102, 102, 102));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 100, 40));

        dataTable.setBackground(new java.awt.Color(255, 250, 202));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "PDL Name", "Time in", "Time out"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 680, 350));

        showDate.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        showDate.setForeground(new java.awt.Color(255, 250, 202));
        showDate.setText("date");
        jPanel1.add(showDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 20));

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 250, 202));
        jLabel2.setText("Current Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 20));

        roundedPanel1.setBackground(new java.awt.Color(255, 250, 202));
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Visitor List");
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 50));

        addVisitor.setBackground(new java.awt.Color(103, 146, 137));
        addVisitor.setForeground(new java.awt.Color(255, 250, 202));
        addVisitor.setText("Add Visitor");
        addVisitor.setFocusable(false);
        addVisitor.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        addVisitor.setRound(20);
        addVisitor.setShadowColor(new java.awt.Color(102, 102, 102));
        addVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitorActionPerformed(evt);
            }
        });
        jPanel1.add(addVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        show(false);
        VisitingSchedule form = new VisitingSchedule();
        form.show();
    }//GEN-LAST:event_backButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showDate.setText(formattedDate);
        showData();
    }//GEN-LAST:event_formWindowOpened

    private void addVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitorActionPerformed
        show(false);
       AddVisitor form = new AddVisitor();
       form.show();
    }//GEN-LAST:event_addVisitorActionPerformed
private void showData() {
        // Get the Firestore instance

        // Create a reference to the collection
        CollectionReference collectionRef = db_connect.db.collection("visitor");

        try {
            // Create a query to filter documents based on date_of_visit
            Query query = collectionRef.whereEqualTo("date_of_visit", formattedDate);

            // Execute the query
            ApiFuture<QuerySnapshot> querySnapshot = query.get();

            // Clear the existing rows in the table model
            DefaultTableModel tableModel = (DefaultTableModel) dataTable.getModel();
            tableModel.setRowCount(0);

            // Iterate over the documents in the result set
            for (QueryDocumentSnapshot document : querySnapshot.get().getDocuments()) {
                // Extract data from the document
              

                // Create the row data with the updated time
                Object[] rowData = {
                    document.getString("first_name") + " " + document.getString("last_name"),
                    document.getString("pdl_firstname") + " " + document.getString("pdl_lastname"),
                    document.getString("time_of_visit"),
                    document.getString("time_out"),
                    };

                // Add the row to the table model
                tableModel.addRow(rowData);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "There's a problem in the database.",
                    "Database Error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorList().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomComponents.button.Button addVisitor;
    private CustomComponents.button.Button backButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private CustomComponents.RoundedPanel roundedPanel1;
    private javax.swing.JLabel showDate;
    // End of variables declaration//GEN-END:variables
}
