/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package os_group_3;

import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import java.awt.List;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author johnl
 */
public class VisitingSchedule extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public VisitingSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginButton = new CustomComponents.button.Button();
        loginButton1 = new CustomComponents.button.Button();
        loginButton2 = new CustomComponents.button.Button();
        loginButton3 = new CustomComponents.button.Button();
        loginButton4 = new CustomComponents.button.Button();
        logo = new javax.swing.JLabel();
        roundedPanel1 = new CustomComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OS_Group3");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 53, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(103, 146, 137));
        loginButton.setForeground(new java.awt.Color(255, 250, 202));
        loginButton.setText("Back");
        loginButton.setFocusable(false);
        loginButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        loginButton.setRound(20);
        loginButton.setShadowColor(new java.awt.Color(102, 102, 102));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 40));

        loginButton1.setBackground(new java.awt.Color(103, 146, 137));
        loginButton1.setForeground(new java.awt.Color(255, 250, 202));
        loginButton1.setText("Visit Report");
        loginButton1.setFocusable(false);
        loginButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        loginButton1.setShadowColor(new java.awt.Color(102, 102, 102));
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 270, 90));

        loginButton2.setBackground(new java.awt.Color(103, 146, 137));
        loginButton2.setForeground(new java.awt.Color(255, 250, 202));
        loginButton2.setText("<html> <p style=\"text-align:center\">Add Visitor</p> </html>");
        loginButton2.setFocusable(false);
        loginButton2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        loginButton2.setShadowColor(new java.awt.Color(102, 102, 102));
        loginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 270, 90));

        loginButton3.setBackground(new java.awt.Color(103, 146, 137));
        loginButton3.setForeground(new java.awt.Color(255, 250, 202));
        loginButton3.setText("Visitor List");
        loginButton3.setFocusable(false);
        loginButton3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        loginButton3.setShadowColor(new java.awt.Color(102, 102, 102));
        loginButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 270, 90));

        loginButton4.setBackground(new java.awt.Color(103, 146, 137));
        loginButton4.setForeground(new java.awt.Color(255, 250, 202));
        loginButton4.setText("Visitor Profile");
        loginButton4.setFocusable(false);
        loginButton4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        loginButton4.setShadowColor(new java.awt.Color(102, 102, 102));
        loginButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 270, 90));

        logo.setIcon((new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\images\\bjmpLogo"
            + ".png")));
jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 430, 400));

roundedPanel1.setBackground(new java.awt.Color(255, 250, 202));
roundedPanel1.setRoundBottomRight(20);
roundedPanel1.setRoundTopRight(20);
roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
jLabel1.setForeground(new java.awt.Color(0, 0, 0));
jLabel1.setText("Visiting Schedule");
roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 50));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
            show(false);
            Homepage form = new Homepage();
            form.show();

//        try {
//            String collectionName = "admin";
//            
//            String usernameInput = username.getText();
//            String passwordInput = hashPass.encryptPassword(password.getText());
//         
//            var documents = db_connect.db.collection(collectionName)
//                    .whereEqualTo("username", usernameInput)
//                    .whereEqualTo("password", passwordInput)
//                    .get()
//                    .get()
//                    .getDocuments();
//            
//            if(!documents.isEmpty()){
//                System.out.println("Login successful!");
//            }else{
//                System.out.println("Login failed. Invalid username or password.");
//            }  
//        }
//        catch(Exception e){
//            System.out.print(e);
//         }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        show(false);
        VisitReports form = new VisitReports();
        form.show();
    }//GEN-LAST:event_loginButton1ActionPerformed

    private void loginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton2ActionPerformed
        show(false);
        CheckVisitor form = new CheckVisitor();
        form.show();
    }//GEN-LAST:event_loginButton2ActionPerformed

    private void loginButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton3ActionPerformed
        show(false);
        VisitorList form = new VisitorList();
        form.show();
    }//GEN-LAST:event_loginButton3ActionPerformed

    private void loginButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton4ActionPerformed
        show(false);
        CheckVisitorInformation form = new CheckVisitorInformation();
        form.show();
    }//GEN-LAST:event_loginButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitingSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private CustomComponents.button.Button loginButton;
    private CustomComponents.button.Button loginButton1;
    private CustomComponents.button.Button loginButton2;
    private CustomComponents.button.Button loginButton3;
    private CustomComponents.button.Button loginButton4;
    private javax.swing.JLabel logo;
    private CustomComponents.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
